--js-flags='--clear-free-memory --single-threaded-gc' 
--disable-gpu 
--enable-features=ChromeRefresh2023 
--disable-software-rasterizer 
--disable-smooth-scrolling 
--gpu-sandbox-failures-fatal=yes 
--ozone-platform=wayland 
