--ozone-platform-hint=auto 
--js-flags='--jitless --clear-free-memory --single-threaded-gc' 
--disable-gpu 
--disable-software-rasterizer 
--disable-smooth-scrolling 
--gpu-sandbox-failures-fatal=yes 
