--js-flags='--jitless --clear-free-memory --single-threaded-gc' 
--disable-gpu 
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,ChromeRefresh2023 
--disable-software-rasterizer 
--disable-smooth-scrolling 
--gpu-sandbox-failures-fatal=yes 
--ozone-platform=wayland 
#--use-gl=angle 
#--use-angle=gl 
