--js-flags='--clear-free-memory --single-threaded-gc' 
--disable-smooth-scrolling 
--ozone-platform=wayland 
--use-gl=angle 
--use-angle=gl 
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,ChromeRefresh2023 
